-- Generated by nwg-displays on 2026-07-03 at 09:25:49. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "2805x960",
    scale = 1.5
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1200@59.95",
    position = "2671x0",
    scale = 1.25
})
